import React from "react";
import moment from "moment";
import Image from "next/image";
import logo from "@/src/assets/img/logo.png";
import { TMedicalReport } from "@/src/types/medicalReport.type";
import { Divider } from "@heroui/divider";
import { firstLetterCapital } from "@/src/utils/firstLetterCapital";

const InvoicePDF = ({
  printContentRef,
  medicalReport,
}: {
  printContentRef: React.RefObject<HTMLDivElement>;
  medicalReport: TMedicalReport;
}) => {
  const { doctor, patient, appointment } = medicalReport;
  const payment = appointment?.payment;

  return (
    <div
      id="printContent"
      ref={printContentRef}
      className="px-10 py-6 text-[16px] text-black"
    >
      {/* Header */}
      <div className="flex justify-between items-center mb-6">
        <div>
          <h1 className="text-2xl font-bold mb-1">Invoice</h1>
          <p className="text-gray-700">DocEye Health Services</p>
          <p className="text-sm text-gray-500">
            {moment(medicalReport.createdAt).format("DD MMM YYYY")}
          </p>
          <p className="text-gray-700">
            <strong>Payment Id: </strong>
            {medicalReport?.appointment?.payment?._id}
          </p>
        </div>
        <div className="flex justify-end items-center">
          <Image src={logo} height={40} width={40} alt="logo" />
        </div>
      </div>

      <Divider className="my-4" />

      {/* Doctor & Patient Info */}
      <div className="grid grid-cols-2 gap-4 mb-6">
        <div>
          <h2 className="font-semibold mb-1">Billed To:</h2>
          <p>{patient.name}</p>
          <p>{patient.gender}</p>
          <p>{patient.email}</p>
        </div>
        <div className="text-right">
          <h2 className="font-semibold mb-1">Doctor Info:</h2>
          <p>
            {doctor.doctorTitle} {doctor.name}
          </p>
          <p>
            {doctor.doctorType} — {doctor.medicalDegree}
          </p>
          <p>Reg. No: {doctor.doctorCode}</p>
        </div>
      </div>

      {/* Appointment Info */}
      <div className="mb-6">
        <h2 className="font-semibold mb-2">Appointment Details</h2>
        <p>
          Appointment Type:{" "}
          <span className="font-medium">
            {firstLetterCapital(appointment?.appointmentType)}
          </span>
        </p>
        <p>
          Schedule:{" "}
          {moment(appointment?.schedule).format("DD MMM YYYY ⏰ hh:mm A")}
        </p>
        <p>Status: {firstLetterCapital(appointment?.status)}</p>
        <p>Payment Method: {payment?.paymentMethod}</p>
      </div>

      {/* Payment Breakdown */}
      <div className="mb-6">
        <h2 className="font-semibold mb-2">Payment Summary</h2>
        <div className="border rounded-md overflow-hidden w-full">
          <table className="w-full border-collapse text-left text-md font-semibold text-paragraph">
            <thead className="bg-gray-100">
              <tr>
                <th className="p-2 border">Description</th>
                <th className="p-2 border text-right">Amount (৳)</th>
              </tr>
            </thead>
            <tbody>
              <tr className="even:bg-gray-50">
                <td className="p-2 border">Consultation Fee</td>
                <td className="p-2 border text-right">
                  {payment?.amount?.consultationFee || 0}
                </td>
              </tr>
              <tr className="even:bg-gray-50">
                <td className="p-2 border">VAT</td>
                <td className="p-2 border text-right">
                  {payment?.amount?.vat || 0}
                </td>
              </tr>
              <tr className="even:bg-gray-50">
                <td className="p-2 border">Platform Fee</td>
                <td className="p-2 border text-right">
                  {payment?.amount?.platformFee || 0}
                </td>
              </tr>
              <tr className="font-bold text-xl">
                <td className="p-2 border">Total</td>
                <td className="p-2 border text-right">
                  {payment?.amount?.total || 0}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <Divider className="my-6" />

      {/* Footer */}
      <div className="text-right">
        <h2 className="font-semibold text-lg">
          {doctor.doctorTitle} {doctor.name}
        </h2>
        <p>{doctor.doctorType}</p>
        <p className="text-sm text-gray-600">DocEye</p>
      </div>

      <div className="text-center mt-10 text-sm text-gray-500">
        <p>Invoice generated by DocEye</p>
        <p>Powered by ❤️ Habib Utsho</p>
      </div>
    </div>
  );
};

export default InvoicePDF;
